imports:
    - { resource: config.yml }
    - { resource: loaders.yml }
    - { resource: plugins.yml }

services:
    Hostnet\Bundle\WebpackBundle\CacheWarmer\WebpackCompileCacheWarmer:
        arguments:
            - '@Hostnet\Component\Webpack\Asset\CacheGuard'
        tags:
            - { name: "kernel.cache_warmer", priority: 10 }

    Hostnet\Bundle\WebpackBundle\Command\CompileCommand:
        arguments:
            - '@Hostnet\Component\Webpack\Asset\CacheGuard'
        tags:
            - { name: "console.command" }

    Hostnet\Component\Webpack\Asset\CacheGuard:
        arguments:
            - '@Hostnet\Component\Webpack\Asset\Compiler'
            - '@Hostnet\Component\Webpack\Asset\Dumper'
            - '@Hostnet\Component\Webpack\Asset\Tracker'
            - '@logger'

    Hostnet\Component\Webpack\Asset\TemplateFinder:
        arguments:
            - '@kernel'
            - '%kernel.root_dir%/Resources'

    Hostnet\Component\Webpack\Asset\Tracker:
        public: true
        arguments:
            - '@Hostnet\Component\Webpack\Profiler\Profiler'
            - '@Hostnet\Component\Webpack\Asset\TemplateFinder'
            - "%kernel.root_dir%"
            - "" # asset_path
            - "" # output dir
            - [] # bundles

    Hostnet\Component\Webpack\Asset\Dumper:
        public: true
        arguments:
            - '@filesystem'
            - '@logger'
            - [] # bundles
            - "" # "public" dir
            - "" # output dir

    Symfony\Component\Process\Process:
        public: true
        arguments:
            - "" # Node binary
            - "" # Cache directory

    Hostnet\Component\Webpack\Asset\TwigParser:
        arguments:
            - '@Hostnet\Component\Webpack\Asset\Tracker'
            - '@twig'
            - "%kernel.cache_dir%"

    Hostnet\Component\Webpack\Asset\Compiler:
        public: true
        arguments:
            - '@Hostnet\Component\Webpack\Profiler\Profiler'
            - '@Hostnet\Component\Webpack\Asset\Tracker'
            - '@Hostnet\Component\Webpack\Asset\TwigParser'
            - '@Hostnet\Component\Webpack\Configuration\ConfigGenerator'
            - '@Symfony\Component\Process\Process'
            - "%kernel.cache_dir%"
            - [] # bundles
            - '@?debug.stopwatch'

    Hostnet\Bundle\WebpackBundle\Twig\TwigExtension:
        public: true
        arguments:
            - '@twig.loader'
            - "" # web_path
            - "" # public_path
            - "" # dump_path
            - "" # common_js
            - "" # common_css
        tags:
            - { name: "twig.extension" }

    Hostnet\Component\Webpack\Configuration\ConfigGenerator:
        public: true

    Hostnet\Component\Webpack\Profiler\Profiler: ~

    # BC aliases
    hostnet_webpack.bridge.twig_extension: '@Hostnet\Bundle\WebpackBundle\Twig\TwigExtension'
    hostnet_webpack.bridge.profiler: '@Hostnet\Component\Webpack\Profiler\Profiler'
    hostnet_webpack.bridge.asset_compiler: '@Hostnet\Component\Webpack\Asset\Compiler'
    hostnet_webpack.bridge.asset_twig_parser: '@Hostnet\Component\Webpack\Asset\TwigParser'
    hostnet_webpack.bridge.compiler_process: '@Symfony\Component\Process\Process'
    hostnet_webpack.bridge.asset_dumper: '@Hostnet\Component\Webpack\Asset\Dumper'
    hostnet_webpack.bridge.cache_warmer: '@Hostnet\Bundle\WebpackBundle\CacheWarmer\WebpackCompileCacheWarmer'
    hostnet_webpack.bridge.generate_config_command: '@Hostnet\Bundle\WebpackBundle\Command\CompileCommand'
    hostnet_webpack.bridge.config_generator: '@Hostnet\Component\Webpack\Configuration\ConfigGenerator'
    hostnet_webpack.bridge.asset_cacheguard: '@Hostnet\Component\Webpack\Asset\CacheGuard'
    hostnet_webpack.bridge.asset_tracker: '@Hostnet\Component\Webpack\Asset\Tracker'
